### ISSUE TITLE
Support for string tables

### ISSUE THREAD

**Issue by scriptease** [igorkulman/iOSLocalizationEditor#1]
Hello,

first of all thanks for the great app!

In our App we use not just Localizable.string, but string tables as well.
I would love to see a support for for string table files as well!

Kind regards,
Florian

**Comment by igorkulman** [comment]
Hi, I can imagine two implementations

1. Upon detecting multiple strings files the app would show a dialog making the user choose which strings file to open (Localizable.string vs some other .string files)
2. Opening multiple windows where each window is a different strings file (table)

I think I can try to do 1., 2. seems like to much work for this use case. But PRs are always welcomed.

**Comment by scriptease** [comment]
Thanks for the quick answer!

I thought about collecting the [Localization] by name of the strings file and adding a dropdown of some kind to switch between them.

Something like 

`    let localizationFiles = Dictionary(grouping: folder.makeFileSequence(recursive: true).filter { file in
            return file.name.hasSuffix(".strings") && ignoredDirectories.map({file.path.contains("\($0)/")}).filter({$0}).count == 0
        }, by: {$0.path.components(separatedBy:"/").filter({!$0.hasSuffix(".lproj")}).joined(separator:"/")})`

I might look at it again a little later.

**Comment by scriptease** [comment]
I made some changes in my fork : https://github.com/scriptease/iOSLocalizationEditor
- I created a LocalizationGroup to contain the previous data model for each localised file
- Per default it selects the Localizable.strings file as before
- If there are multiple files a select menu is added to the Menu bar
- The title of the app reflects the name of the strings file

**Comment by igorkulman** [comment]
Fixed by #2
