### ISSUE TITLE
Tab vertically through list not possible

### ISSUE THREAD

**Issue by misteu** [igorkulman/iOSLocalizationEditor#103]
You should be able to somehow tab vertically through the list without leaving the keyboard.

Currently, I can only tab horizontally through the list.

**Comment by NikKovIos** [comment]
I can scroll the both directions.

**Comment by misteu** [comment]
Ok then nevermind. Maybe I pressed the wrong keys.

I am not on my machine right now.

How did you vertically move through it? I mean which keys did you press?

**Comment by Svec-Tomas** [comment]
I guess this is the feature (shortcut) I am missing as well. I can not find out myself how can I jump from one field to another. TAB or arrow keys not working. CheetSheat or KeyClue also not showing any shortcuts made for this purpose.

**Comment by Svec-Tomas** [comment]
Ahoj Igor, thanks a lot for your work and for this app! I am just an ordinary user and I am not sure how or where to download the latest version with the implemented feature. Can you help (guide) me a little bit, please?

**Comment by igorkulman** [comment]
> Ahoj Igor, thanks a lot for your work and for this app! I am just an ordinary user and I am not sure how or where to download the latest version with the implemented feature. Can you help (guide) me a little bit, please?

Try 
[LocalizationEditor.zip](https://github.com/igorkulman/iOSLocalizationEditor/files/13772821/LocalizationEditor.zip)

**Comment by Svec-Tomas** [comment]
Working great for me Igor on Sonoma 14.2.1. TAB - next, SHIFT + TAB - previous field. Thanks a lot!

**Comment by igorkulman** [comment]
Included in the v2.9.2 release
