### ISSUE TITLE
No more build artifact?

### ISSUE THREAD

**Issue by daeho-ro** [igorkulman/iOSLocalizationEditor#106]
I cannot see the .app.zip file on the release note and so the brew cannot be updated either.
Any plan to add the build file again?

**Comment by daeho-ro** [comment]
brew can see the new version but cannot download because the new version artifact is not there.
```
> brew lc localizationeditor
localizationeditor: 2.9 ==> 2.9.2
```

So I added a PR to change the build trigger from PR to tag pushed and then the next version will be automatically built, I guess.

**Comment by igorkulman** [comment]
Sorry, looks like the file was there but in some weird error state, I uploaded it again.
