### ISSUE TITLE
hard to build

### ISSUE THREAD

**Issue by ishall1** [igorkulman/iOSLocalizationEditor#3]
i think a good open source project should be easy to build. But this project is hard to build! So i give up.

**Comment by igorkulman** [comment]
I think it is quite easy to build, you just need to look at the README file

1. Run `carthage bootstrap` tp get the dependencies (just once)
2. Open and build the project in Xcode

Of course, if you are not an iOS / macOS developer it might be a problem, but the developers are the target audience for the tool.

**Comment by ishall1** [comment]
error: Signing for "LocalizationEditor" requires selecting either a development team or a provisioning profile. Select a development team or a provisioning profile in the project editor. (in target 'LocalizationEditor')

**Comment by igorkulman** [comment]
The error is self-explanatory, you need to use your provisioning profile.

**Comment by ishall1** [comment]
> I think it is quite easy to build, you just need to look at the README file
> 
> 1. Run `carthage bootstrap` tp get the dependencies (just once)
> 2. Open and build the project in Xcode
> 
> Of course, if you are not an iOS / macOS developer it might be a problem, but the developers are the target audience for the tool.

i have solved the problem. thank you!

**Comment by ishall1** [comment]
> The error is self-explanatory, you need to use your provisioning profile.

it's the first time that i set that option by myself in a third party project.sorry for my word and thank you
