### ISSUE TITLE
App generates invalid localization file

### ISSUE THREAD

**Issue by frogg** [igorkulman/iOSLocalizationEditor#35]
Out of this…
<img width="411" alt="image" src="https://user-images.githubusercontent.com/5204169/53913510-cacaca00-405b-11e9-8267-4f7cf87e6be3.png">

…this is generated:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/5204169/53913440-a53dc080-405b-11e9-913c-dcc059c56300.png">

**Comment by igorkulman** [comment]
The `//` comments are not supported at the moment, just `/* */` but the app should just ignore them, I will take a look at this.

**Comment by frogg** [comment]
Ah ok, thanks! I think the main problem is that I’m using quotes within the // comment
