### ISSUE TITLE
Long text in key cell overlaps with localization cell

### ISSUE THREAD

**Issue by frogg** [igorkulman/iOSLocalizationEditor#39]
<img width="1792" alt="screen shot 2019-03-06 at 22 27 05" src="https://user-images.githubusercontent.com/5204169/53914913-031fd780-405f-11e9-8084-eeb4b7a180d7.png">

**Comment by igorkulman** [comment]
What is the key in the screenshot exactly? Because I cannot reproduce with just a random long key.

**Comment by frogg** [comment]
This is the key with the red circle around:
```
"%@, you climbed %@%@ which is %@ %@ with %@%@."
```

**Comment by igorkulman** [comment]
I cannot reproduce even with your key. I think it is related to the number of columns and the crappy auto-layout on the table view.

**Comment by L1cardo** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/33802186/67212373-dfbf6680-f44e-11e9-9ccc-aebf71c1efa0.png)

**Comment by flemingm** [comment]
I have adjust the keycell to wrap and allow for selection of key.
NOTE: Wrapping will not work well due to message area below. User will need to widen the column.
