### ISSUE TITLE
Text in cells should not appear escaped

### ISSUE THREAD

**Issue by tempelmann** [igorkulman/iOSLocalizationEditor#50]
Might be related to #46 - I see the same issue with single quotes, at least in v2.1 (can't use the latest because I'm on 10.13 and can't build for Swift 5).

Apart from that - great tool! Thanks for making it available. I am using it for a macOS app. Meaning you could advertise this to be useful for both Apple platforms, not just for iOS.

I also added a link to here on quora, where I ended up first, looking for this kind of tool: https://www.quora.com/What-is-the-best-translation-tool-for-Mac

**Comment by igorkulman** [comment]
Could you post a sample strings file? I will check it out.

**Comment by tempelmann** [comment]
Simple as this:

> "example" = "Test\'s";

**Comment by tempelmann** [comment]
Oh - the same issue appears with \\? (backslash + question mark). There may be more. Basically, you should scan any sting for backslashes, and whenever you encounter one, you need to handle the next char specially, and then remove the first backslash. The algorithm for handling the next char would be: If it's "n" or "r", create a LF. Otehrwise, just keep the char (so that \\n turns into a LF, and \\\\ turns into \\, and \\x turns into x, and so on).

**Comment by tempelmann** [comment]
I also see a few other small issues (the document does not show when it's "dirty" (i.e. modified), the Open menu should use "…", menu should be uppercase: "Select All", and so on. Small stuff, but attention to detail is important for a tool that's used for getting these things right :)

I'll set it up on my other Mac that runs 10.14 so that I can supply some changes.

**Comment by igorkulman** [comment]
All PRs are welcome, even for small stuff like adding "..." to a menu item.

**Comment by igorkulman** [comment]
I did some research and experiments and it looks like only double quotes need to escaped and double quotes like `"test" = "Testing \"quotes\"";` work properly in the app.

You are right that `"example" = "It\'s its";` does not work properly, but you do not have to escape the single quote. If I use `"example" = "It's its";` in a real iOS app, it gets handled properly, same with a question mark or a backslash.

I would prefer not to handle escaping of stuff that is not necessary in the app.

**Comment by tempelmann** [comment]
Thanks for doing the research. I agree that escaping of single quotes is not necessary, but some tools write them regardless. That's why you should still handle them.

Also, assuming you do not have to unescape everything is a common rookie mistake (I've seen this many times). Consider this:

You have to escape the backslash. So, it the user enters `\` into a text field, you need to write it as `\\`. Agreed?

Now, to perform this replacement, you need to find any `\` and convert it into `\\`. But what if you leave other escaped strings in the text, like `\?`? You'd end up writing it back as `\\?`, which is equally wrong.

That's why you need to do what I wrote earlier: You need to unescape ANY occurance of \, but you do not need to re-escape any but the required ones (which are double quote, CR and LF, at least).

Okay?

I have posted an unescaping function here, though it's in ObjC, sorry: https://stackoverflow.com/a/56273342/43615

**Comment by igorkulman** [comment]
Yes I agree that the app should not show escaped character with "\" even if the escaping in the string file is not needed but is there. 

I cannot really read Obj-C, Swift version would be better.

**Comment by tempelmann** [comment]
Isn't it quite easy to include ObjC files into Swift? The code I posted could be added as an ObjC class and then you can call it from Swift, I believe. I haven't done this myself, and I'm currently super busy with my own project code, though once I start working on the localization I might pull your project and try to add this.

**Comment by igorkulman** [comment]
Integrating a ObjC file is not a problem. The problem is I just do not want to copy paste a block of code I cannot even read to the project.

**Comment by igorkulman** [comment]
Take a look at #55, ideally try it on your data, works on some escaped strings I tried.
