### ISSUE TITLE
it can not work at macos 10.15

### ISSUE THREAD

**Issue by garryzhong** [igorkulman/iOSLocalizationEditor#57]
i updated system last day, and your tools not work, can you fix

**Comment by igorkulman** [comment]
Could you be more specific?

**Comment by garryzhong** [comment]
UI is wrong while opening strings of xib

**Comment by igorkulman** [comment]
Screenshot? OS version?

**Comment by garryzhong** [comment]
macOS, 10.15

![image](https://user-images.githubusercontent.com/5044230/66633648-e32c4400-ec3d-11e9-9445-98f5dd26c16d.png)

**Comment by igorkulman** [comment]
I do not use Catalina and will not be updating for some time. Feel free to send a PR with a fix.
