### ISSUE TITLE
Path containing part of ignoredDirectories name results in find no .string

### ISSUE THREAD

**Issue by flemingm** [igorkulman/iOSLocalizationEditor#63]
I had a path that contain all my current builds with folder called builds.
I could not load any localizations.

The fix was to include the "/" for the folder

changing:
 private let ignoredDirectories: Set<String> = ["Pods", "Carthage", "build", ".framework"]

to:
 private let ignoredDirectories: Set<String> = ["Pods/", "Carthage/", "build/", ".framework"]

I will issue pull request.

**Comment by flemingm** [comment]
pull request #64

**Comment by igorkulman** [comment]
Thanks for the PR
