### ISSUE TITLE
Order of key and comment is not respected

### ISSUE THREAD

**Issue by flemingm** [igorkulman/iOSLocalizationEditor#68]
Any changes (update or add key) to the input file, results in all key being sorted in the output file.
.
Results in comments originally at top of file being moved to new location if the 1st key is not alphabetically at the top of the list.

Maybe we can have option to have current behaviour or stable input -> update version.
Do not know code well enough yet to know how hard this will be.

**Comment by igorkulman** [comment]
I thought about it when starting the project but it was more complicated than just sorting the data by key. My rationale was that yes the first commit after starting using the app be a bit confusing but then everything will be OK and actually better in your data.
