### ISSUE TITLE
App removes translations when adding a new key

### ISSUE THREAD

**Issue by Schlabbi** [igorkulman/iOSLocalizationEditor#70]
When adding a new key, the app clears all translations of all keys which have been added since the start of the app.

Reproduction steps:

1. Add a new key "A", insert some strings for the translation of this key.
2. Add a new key with any name, translations of the key "A" are now gone.

Workarounds: 
- Restart app after adding a new key and its translations
- First add all keys, then add all translations

**Comment by Schlabbi** [comment]
Closing this issue, this is an issue on the version available via homebrew but not on the current version in this git project.

**Comment by igorkulman** [comment]
Are you sure abiut this? Brew should include 2.3 and looking at diff between 2.3 and master there is basically no code change at all. Just Readme, icons and your storyboard fix.

**Comment by Schlabbi** [comment]
Actually, looking at it again something weird is going on here. Brew installed "Version 2.3 (230)", where I could reproduce the issue.

However, earlier when looking into it with a cloned version of this repo I couldn't reproduce it at all. Now (after cleaning the build dir) I am able to reproduce it again... will look into it more closely.

**Comment by Schlabbi** [comment]
Pinpointed the issue and fixed it. Will open a pull request soon.
