### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by sergeykushner** [igorkulman/iOSLocalizationEditor#79]
Big Sur style icon (made on the basis of the official Apple template)?
https://www.icloud.com/iclouddrive/06r1VhsZTfyzUiCAHChxY473A#AppIcon

**Comment by igorkulman** [comment]
Looks nice, was it made be you so you have all the "rights" to it?

**Comment by sergeykushner** [comment]
Yes. I did it myself. I can later send the file to the source in Sketch.

**Comment by igorkulman** [comment]
Great, I can add it to the project later when I have some time or feel free to create a PR.

**Comment by sergeykushner** [comment]
I can add it myself and make a pull request.

**Comment by igorkulman** [comment]
Sure, go ahead. I like the icon so I will merge it and give you credit for it in README
