### ISSUE TITLE
Export? Multiple Selection?

### ISSUE THREAD

**Issue by onuryurtturk** [igorkulman/iOSLocalizationEditor#87]
Can multiple selection and export to Excel features be supported?

**Comment by igorkulman** [comment]
What exactly do you mean by multiple selection?

Any export is possible but exporting the data into Excel seems like a very uncommon case so it does not seem to be like worth investing my energy in.

**Comment by onuryurtturk** [comment]
I need to transfer the non-translated columns that we compare between the two languages to a place with the keys so that the translation office can translate it into the target language according to its equivalent in the current language. 

Excel was one of the examples I gave. My goal is to transfer missing translations on a column basis. As far as I can see, there is no select all option available, neither for keys nor values.

**Comment by igorkulman** [comment]
This app is intended as a localization editor, hence the name, not as a general tool to import and export data for processing elsewhere
